version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cinewithdocker-frontend
    ports:
      - "80:80" 
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_PORT}
    networks:
      - cine_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cinewithdocker-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      - PORT=${BACKEND_PORT}
    networks:
      - cine_net

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cine_net

volumes:
  postgres_data:

networks:
  cine_net:
    driver: bridge
